# Profil DOCKER - Gateway Service
spring.application.name=Gateway-Service
server.port=8090

# EUREKA (Docker)
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# SECURITE JWT
security.jwt.secret=${JWT_SECRET}

# TAILLE MAX DES REQUETES
spring.codec.max-in-memory-size=50MB

# GATEWAY FILTER
spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials RETAIN_FIRST

# LOGS
logging.level.org.springframework.cloud.gateway=INFO
logging.level.reactor.netty.http.client=INFO

# MONITORING
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
