apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-service
  namespace: fakarni-prod
  labels:
    app: eureka-service
    app.kubernetes.io/part-of: fakarniapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: eureka-service
    spec:
      containers:
        - name: eureka-service
          image: fakarnicr.azurecr.io/fakarni-eureka-service:latest
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "300m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 60
            periodSeconds: 15
