apiVersion: apps/v1
kind: Deployment
metadata:
  name: geofencing-service
  namespace: fakarni-prod
  labels:
    app: geofencing-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: geofencing-service
  template:
    metadata:
      labels:
        app: geofencing-service
    spec:
      containers:
        - name: geofencing-service
          image: fakarnicr.azurecr.io/fakarni-geofencing-service:latest
          ports:
            - containerPort: 9012
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: fakarni-common-config
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://fakarni-mysql.mysql.database.azure.com:3306/db_geofencing?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=true"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: fakarni-common-config
                  key: MYSQL_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fakarni-secrets
                  key: MYSQL_PASSWORD
            - name: SPRING_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: fakarni-secrets
                  key: MAIL_USERNAME
            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fakarni-secrets
                  key: MAIL_PASSWORD
            - name: TWILIO_ACCOUNT_SID
              valueFrom:
                secretKeyRef:
                  name: fakarni-secrets
                  key: TWILIO_ACCOUNT_SID
            - name: TWILIO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: fakarni-secrets
                  key: TWILIO_AUTH_TOKEN
            - name: TWILIO_FROM_NUMBER
              valueFrom:
                secretKeyRef:
                  name: fakarni-secrets
                  key: TWILIO_FROM_NUMBER
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "400m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9012
            initialDelaySeconds: 40
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9012
            initialDelaySeconds: 70
            periodSeconds: 15
