apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: fakarni-prod
  labels:
    app: user-service
    app.kubernetes.io/part-of: fakarniapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: fakarnicr.azurecr.io/fakarni-user-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: fakarni-common-config
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: fakarni-secrets
                  key: MONGODB_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: fakarni-secrets
                  key: JWT_SECRET
            - name: MAIL_USERNAME_USER
              valueFrom:
                secretKeyRef:
                  name: fakarni-secrets
                  key: MAIL_USERNAME_USER
            - name: MAIL_PASSWORD_USER
              valueFrom:
                secretKeyRef:
                  name: fakarni-secrets
                  key: MAIL_PASSWORD_USER
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: fakarni-secrets
                  key: GOOGLE_CLIENT_ID
            - name: FACEBOOK_APP_ID
              valueFrom:
                secretKeyRef:
                  name: fakarni-secrets
                  key: FACEBOOK_APP_ID
            - name: FACEBOOK_APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: fakarni-secrets
                  key: FACEBOOK_APP_SECRET
            - name: APP_FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  name: fakarni-common-config
                  key: APP_FRONTEND_URL
          resources:
            requests:
              memory: "384Mi"
              cpu: "150m"
            limits:
              memory: "768Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 40
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 70
            periodSeconds: 15
