apiVersion: v1
kind: Service
metadata:
  name: activite-educative-service
  namespace: fakarni-prod
spec:
  selector:
    app: activite-educative-service
  ports:
    - port: 8084
      targetPort: 8084
  type: ClusterIP
