apiVersion: v1
kind: Service
metadata:
  name: detection-maladie-service
  namespace: fakarni-prod
spec:
  selector:
    app: detection-maladie-service
  ports:
    - port: 8058
      targetPort: 8058
  type: ClusterIP
