apiVersion: v1
kind: Service
metadata:
  name: geofencing-service
  namespace: fakarni-prod
spec:
  selector:
    app: geofencing-service
  ports:
    - port: 9012
      targetPort: 9012
  type: ClusterIP
