apiVersion: v1
kind: Service
metadata:
  name: meeting-insights-service
  namespace: fakarni-prod
spec:
  selector:
    app: meeting-insights-service
  ports:
    - port: 8096
      targetPort: 8096
  type: ClusterIP
