# CI â€” Group Service (Groupes + JWT + MySQL)
name: CI â€” Group Service

on:
  push:
    branches: [main, develop]
    paths:
      - 'backend/group/**'
      - '.github/workflows/ci-group-service.yml'
  pull_request:
    branches: [main]
    paths:
      - 'backend/group/**'

jobs:
  ci:
    uses: ./.github/workflows/ci-reusable.yml
    with:
      service-name: "Group Service"
      service-path: "backend/group"
      image-name: "fakarni-group-service"
      sonar-project-key: "fakarni-group-service"
      is-java: true
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
      CONTAINER_APPS_ENV: ${{ secrets.CONTAINER_APPS_ENV }}